api/urls.py
from django.urls import path

# from api.views import BookReviewDetailApiView, BookListAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewViewSet


app_name = 'api'
router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')

urlpatterns = router.urls


# urlpatterns = [
#     path('reviews/', BookListAPIView.as_view(), name='review_list'),
#     path('reviews/<int:id>/', BookReviewDetailApiView.as_view(), name='review_detail')
# ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),

    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),

]
static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),

    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default='default_profile_pic.jpg')

users/forms.py
from django import forms

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()



class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserCreateForm, UserUpdateForm


class RegisterView(View):

    def get(self, request):
        create_form = UserCreateForm()
        context = {
            'form': create_form
        }
        return render(request, 'users/register.html', context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'users/register.html', context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, 'users/login.html', {'login_form': login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You have successfully logged in.')
            return redirect('books:list')

        else:
            return render(request, 'users/login.html', {'login_form': login_form})


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/profile.html', {'user': request.user})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, 'You have successfully logged out.')
        return redirect('landing_page')


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, 'users/profile_edit.html', {'form': user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(instance=request.user, data=request.POST, files=request.FILES)

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, 'You have successfully updated your profile.')

            return redirect('users:profile')
        
        return render(request, 'users/profile_edit.html', {'form': user_update_form})

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}Login Page{% endblock %}

{% block content %}
    <h3>Login page</h3>

    <div class="row">
        <div class="col-4">
                <form method="post">
                    {% csrf_token %}
                    {{ login_form | crispy }}

                    <button type="submit" class="btn btn-primary">Log in</button>  <span class="ms-3">No account? Then, <a href="{% url 'users:register' %}">get registered</a> </span>
                </form>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Profile page{% endblock %}

{% block content %}
    <h3>
      Profile page
    </h3>

        <div class="container mt-4 mb-4 p-3 d-flex justify-content-center">

            <div class=" image d-flex flex-column justify-content-center align-items-center">
                <button class="btn btn-secondary">
                    <img class="profile-pic" src="{{ user.profile_picture.url }}" alt="Profile picture">
                </button> <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
                <span class="idd">@{{ user.username }}</span>
                <span class="idd">{{ user.email }}</span>

                <div class=" d-flex mt-2">
                    <div>
                        <a class="btn btn-dark" href="{% url 'users:profile_edit' %}">edit profile</a>
                    </div>
                </div>
                <div class=" px-2 rounded mt-4 date">
                    <span class="join">Joined {{ user.data_joined |date:"M d, Y" }}</span>
                </div>

            </div>

        </div>

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h3>Edit profile </h3>

    <div class="row">
        <div class="col-5">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}

                <button class="btn btn-primary">save changes</button>
            </form>

        </div>
    </div>




{%endblock%}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock %}

{% block content %}
    <h3>Register Page</h3>

    <div class="row">
        <div class="col-4">
                <form method="post" action="{% url 'users:register' %}">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-success" type="submit">Submit</button>
                </form>
        </div>
    </div>



{% endblock %}