api/urls.py
from django.urls import path

# from api.views import BookReviewDetailApiView, BookListAPIView
from rest_framework.routers import DefaultRouter
from api.views import BookReviewViewSet


app_name = 'api'
router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')

urlpatterns = router.urls


# urlpatterns = [
#     path('reviews/', BookListAPIView.as_view(), name='review_list'),
#     path('reviews/<int:id>/', BookReviewDetailApiView.as_view(), name='review_detail')
# ]

books/urls.py
from django.urls import path
from .views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteView, DeleteReviewView

app_name = 'books'
urlpatterns = [
    path('', BooksView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit', EditReviewView.as_view(), name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/confirm', ConfirmDeleteView.as_view(),
         name='confirm_delete_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(),
         name='delete_review'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),

    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),

]
static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path('', landing_page, name='landing_page'),
    path('home/', home_page, name='home_page'),

    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit'),

]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url  %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile_edit' as profile_edit_page_url %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads clone{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">

</head>
<body class="mx-5">

<nav class="navbar navbar-expand-lg bg-body-tertiary mb-2 navbar bg-primary" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads Clone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
            <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
        </li>

      </ul>

        <div class="me-5">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav me-5">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.username }}
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ profile_page_url }}">Profile</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                        </ul>
                    </li>
                </ul>


<!--                {{ request.User.Username }}-->
            {% else %}
                <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Login</a>

            {% endif %}

        </div>
    </div>
  </div>
</nav>


<div class="container">
    {% if messages %}
    <div class="mt-4">
        {% for message in messages %}

            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>

    {% endif %}

    {% block content %}{% endblock %}
</div>





<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block title %}Home Page{% endblock %}

{% block content %}
    <h3>All reviews</h3>

    {% for review in page_obj %}
      <div class="container posts-content">
          <div class="row">
              <div class="col-lg-6">
                  <div class="card mb-4">
                    <div class="card-body">
                      <div class="media mb-3">
                        <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                        <div class="media-body ml-3">
                          <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                          <div class="text-muted small">{{ review.created_at | date:'M, d, Y' }}</div>
                        </div>
                      </div>

                      <p>
                        {{ review.comment | truncatechars:300 }}
                      </p>
                      <img src="{{ review.book.cover_picture.url }}" class="center">
                    </div>

                  </div>
              </div>
          </div>
      </div>
    {% endfor %}

    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="#">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last&raquo;</a></li>
            {% endif %}

        </ul>

    </nav>

{% endblock %}

templates/landing.html
{% extends 'base.html' %}

{% block content %}
    <h1>Landing Page</h1>
    <p> Who We Are
        Goodreads is the world’s largest site for readers and book recommendations.
        Our mission is to help readers discover books they love and get more out of reading.
        Goodreads launched in January 2007.

        A Few Things You Can Do On Goodreads
        See what books your friends are reading.
        Track the books you're reading, have read, and want to read.
        Check out your personalized book recommendations.
        Our recommendation engine analyzes 20 billion data points to give suggestions tailored to your literary tastes.
        Find out if a book is a good fit for you from our community’s reviews.
    </p>

{% endblock %}